demo/urls.py
import django


from django.urls import path
from demo import views
urlpatterns=[
    path('register/',views.register,name="register"),
    path('update/<pk>/',views.update,name="update"),
    path('select/',views.select,name="select"),
    path('delete/<pk>/',views.delete,name="delete")
]

demo2/urls.py
from django.urls import path
from demo2 import views
urlpatterns=[
    path('register/',views.registerview,name="register"),
    path('update/<pk>/',views.updateview,name="update"),
    path('select/',views.selectview,name="select"),
    path('delete/<pk>/',views.deleteview,name="delete")
]

demo3/urls.py
from django.urls import path
from demo3 import views
app_name='demo3'

urlpatterns=[
    path('enq/', views.enqview ,name='enq'),
    path('update/<pk>/',views.updateenqview,name='update'),
    path('select/', views.selectenqview ,name='select'),
    path('delete/<pk>/', views.deleteenqview ,name='delete'),
    path('download/', views.download_csv ,name='download'),


]

pro/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('d/',include("demo.urls")),
    path('d2/',include("demo2.urls")),
    path('d3/',include("demo3.urls")),

]

demo/models.py
from django.db import models

# Create your models here.
class registermodel(models.Model):
    username=models.CharField(max_length=30)
    password=models.CharField(max_length=30)
    email=models.EmailField()
    phone=models.BigIntegerField()

demo2/models.py
from django.db import models

# Create your models here.
class regmodel(models.Model):
    username=models.CharField(max_length=30)
    password=models.CharField(max_length=30)
    email=models.EmailField()
    phone=models.BigIntegerField()

demo3/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class enqmodel(models.Model):
    name=models.CharField(max_length=30)
    address=models.CharField(max_length=30)
    phone=models.BigIntegerField()
    email=models.EmailField()
    desc=models.TextField()
    date=models.DateTimeField(default=datetime.now())

demo2/forms.py
from django import forms
from demo2.validators import *

class registerform(forms.Form):
    username=forms.CharField(validators=[namelength])
    password=forms.CharField(widget=forms.PasswordInput,validators=[namelength])
    email=forms.EmailField()
    phone=forms.IntegerField(validators=[phonelength])

demo3/forms.py
from wsgiref.validate import validator
from django import forms
from demo3.models import enqmodel
# from demo3.validator import *

#Create your forms here.
class enqform(forms.ModelForm):
    class Meta:
        model=enqmodel
        fields='__all__'
        #fields=['name','phone','email','address','desc']
        #fields=exclude['address']
    def clean(self):
        name=self.cleaned_data['name']
        if not(3<=len(name)<=15):
            raise forms.ValidationError("Name should be minimum 3 letters and maximum 15 letters")

        phone=self.cleaned_data['phone']
        if not(len(str(phone))==10):
            raise forms.ValidationError("Number should be 10 digits")

demo/views.py
from django.shortcuts import render
from django.http import HttpResponse
from demo.models import registermodel

# Create your views here.
def register(request):
    if request.method=='POST':
        print(request.POST)
        user=request.POST['username']
        pas=request.POST['password']
        email=request.POST['email']
        phone=request.POST['phone']
        registermodel.objects.create(username=user,password=pas,email=email,phone=phone)
        return HttpResponse("record is created")
    return render(request,'register.html')

def update(request,pk):
    res=registermodel.objects.get(id=pk)
    if request.method=='POST':
        print(request.POST)
        user=request.POST['username']
        pas=request.POST['password']
        email=request.POST['email']
        phone=request.POST['phone']
        registermodel.objects.filter(id=pk).update(username=user,password=pas,email=email,phone=phone)
        return HttpResponse("record is updated")
    return render(request,'update.html',{'i':res})

def select(request):
    res=registermodel.objects.all()
    return render(request,'select.html',{'res':res})

def delete(request,pk):
    res=registermodel.objects.get(id=pk).delete()
    return HttpResponse(" Record is deleted")

demo2/views.py
from django.shortcuts import render
from django.http import HttpResponse
from demo2.forms import registerform
from demo2.models import regmodel

# Create your views here.
def registerview(request):
    form=registerform()
    if request.method=='POST':
       form=registerform(request.POST)
       if form.is_valid():
            print(form)
            regmodel.objects.create(username=form.cleaned_data['username'],
            password=form.cleaned_data['password'],
            email=form.cleaned_data['email'],
            phone=form.cleaned_data['phone'])
            return HttpResponse("record is created")
    return render(request,'reg.html',{ 'form':form })

def updateview(request,pk):
    res=regmodel.objects.get(id=pk)
    if request.method=='POST':
       form=registerform(request.POST)
       if form.is_valid():
            print(form)
            regmodel.objects.filter(id=pk).update(username=form.cleaned_data['username'],
            password=form.cleaned_data['password'],
            email=form.cleaned_data['email'],
            phone=form.cleaned_data['phone'])
            return HttpResponse("record is updated")
    return render(request,'upd.html',{ 'i':res })
   

def selectview(request):
    res=regmodel.objects.all()
    return render(request,'sel.html',{'res':res})

def deleteview(request,pk):
    res=regmodel.objects.get(id=pk).delete()
    return HttpResponse(" Record is deleted")

demo3/views.py
import imp
from urllib import response
from django.shortcuts import render,redirect
from django.http import HttpResponse
from demo3.models import enqmodel
from demo3.forms import enqform
import csv

# Create your views here.
def enqview(request):
    form=enqform()
    if request.method=='POST':
        form=enqform(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse("data is created")
    return render(request,'enq.html',{'form':form})

def updateenqview(request,pk):
    res=enqmodel.objects.get(id=pk)
    form=enqform(instance=res)
    if request.method=='POST':
        form=enqform(request.POST,instance=res)
        if form.is_valid():
            form.save()
            return redirect('/d3/select/')

    return render(request,'enq.html',{'form':form})

def selectenqview(request):
    res=enqmodel.objects.all()
    return render(request,'d3sel.html',{'res':res})

def deleteenqview(request,pk):
    res=enqmodel.objects.get(id=pk).delete()
    return redirect('/d3/select/')

def download_csv(request):
    res=enqmodel.objects.all()
    response=HttpResponse(content_type='text/csv')
    response['Content-Disposition']='attachment;filename=enq.csv'
    csv_writer= csv.writer(response)
    csv_writer.writerow(['name','phone','email','address','desc','date'])
    for i in res:
        csv_writer.writerow([i.name,i.phone,i.email,i.address,i.desc,i.date])
    return response

demo/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1> this is registerform / forms concept</h1>
    <form method="post">
        {% csrf_token %}
        <label for="id_username">username</label>
        <input type="text" id="id_username" name="username" required><br>

        <label for="id_password">password</label>
        <input type="password" id="id_password" name="password" required><br>
        
        <label for="id_email">email</label>
        <input type="email" id="id_email" name="email" required><br>

        <label for="id_phone">phone</label>
        <input type="number" id="id_phone" name="phone" required><br>
        <input type="submit" value="register">
    </form>
    </body>
</html>

demo/templates/select.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for i in res %}
    <h1>{{ i.username }},{{ i.password }}, {{ i.email }}, {{i.phone }}, {{ i.id }}</h1>
    {% endfor %}
</body>
</html>

demo/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <label for="id_username">username</label>
        <input type="text" id="id_username" name="username" value= {{ i.username }} ><br>

        <label for="id_password">password</label>
        <input type="password" id="id_password" name="password" value= {{ i.password }}><br>
        
        <label for="id_email">email</label>
        <input type="email" id="id_email" name="email" value= {{ i.email }}><br>

        <label for="id_phone">phone</label>
        <input type="number" id="id_phone" name="phone" value= {{ i.phone }}><br>
        <input type="submit" value="update">
    </form>
</body>
</html>

demo2/templates/reg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Register">
    </form>
</body>
</html>

demo2/templates/sel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for i in res %}
    <h1>{{ i.username }},{{ i.password }}, {{ i.email }}, {{i.phone }}, {{ i.id }}</h1>
    {% endfor %}
</body>
</html>

demo2/templates/upd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <label for="id_username">username</label>
        <input type="text" id="id_username" name="username" value= {{ i.username }} ><br>

        <label for="id_password">password</label>
        <input type="password" id="id_password" name="password" value= {{ i.password }}><br>
        
        <label for="id_email">email</label>
        <input type="email" id="id_email" name="email" value= {{ i.email }}><br>

        <label for="id_phone">phone</label>
        <input type="number" id="id_phone" name="phone" value= {{ i.phone }}><br>
        <input type="submit" value="update">
    </form>
</body>
</html>

demo3/templates/d3sel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>view</title>
</head>
<body>
    <table>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Address</th>
            <th>Desc</th>
            <th>Date</th>
        </tr>
        {% for i in res %}
        <tr>
            <td>{{ i.name }}</td>
            <td>{{ i.email }}</td>
            <td>{{ i.phone }}</td>
            <td>{{ i.address }}</td>
            <td>{{ i.desc }}</td>
            <td>{{ i.date }}</td>
            <td><a href="{% url 'demo3:update' pk=i.id %}">Update</a></td>
            <td><a href="{% url 'demo3:delete' pk=i.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>
    <a href="{% url 'demo3:enq' %}"></a>
    <a href="{% url 'demo3:download' %}"></a>


</body>
</html>

demo3/templates/enq.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Enquiry form</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="enquiry">
    </form>
</body>
</html>